export default [
  {
    id: 0,
    name: 'Frieda',
    picture: 'images/scottish-terrier.jpeg',
    age: 3,
    breed: 'Scottish Terrier',
    location: 'Lisco, Alabama',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 1,
    name: 'Gina',
    picture: 'images/french-bulldog.jpeg',
    age: 3,
    breed: 'Scottish Terrier',
    location: 'Tooleville, West Virginia',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 2,
    name: 'Collins',
    picture: 'images/scottish-terrier.jpeg',
    age: 2,
    breed: 'French Bulldog',
    location: 'Freeburn, Idaho',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 3,
    name: 'Melissa',
    picture: 'images/boxer.jpeg',
    age: 2,
    breed: 'Boxer',
    location: 'Camas, Pennsylvania',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 4,
    name: 'Jeanine',
    picture: 'images/french-bulldog.jpeg',
    age: 2,
    breed: 'French Bulldog',
    location: 'Gerber, South Dakota',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 5,
    name: 'Elvia',
    picture: 'images/french-bulldog.jpeg',
    age: 3,
    breed: 'French Bulldog',
    location: 'Innsbrook, Illinois',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 6,
    name: 'Latisha',
    picture: 'images/golden-retriever.jpeg',
    age: 3,
    breed: 'Golden Retriever',
    location: 'Soudan, Louisiana',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 7,
    name: 'Coleman',
    picture: 'images/golden-retriever.jpeg',
    age: 3,
    breed: 'Golden Retriever',
    location: 'Jacksonwald, Palau',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 8,
    name: 'Nichole',
    picture: 'images/french-bulldog.jpeg',
    age: 2,
    breed: 'French Bulldog',
    location: 'Honolulu, Hawaii',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 9,
    name: 'Fran',
    picture: 'images/boxer.jpeg',
    age: 3,
    breed: 'Boxer',
    location: 'Matheny, Utah',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 10,
    name: 'Leonor',
    picture: 'images/boxer.jpeg',
    age: 2,
    breed: 'Boxer',
    location: 'Tyhee, Indiana',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 11,
    name: 'Dean',
    picture: 'images/scottish-terrier.jpeg',
    age: 3,
    breed: 'Scottish Terrier',
    location: 'Windsor, Montana',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 12,
    name: 'Stevenson',
    picture: 'images/french-bulldog.jpeg',
    age: 3,
    breed: 'French Bulldog',
    location: 'Kingstowne, Nevada',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 13,
    name: 'Kristina',
    picture: 'images/golden-retriever.jpeg',
    age: 4,
    breed: 'Golden Retriever',
    location: 'Sultana, Massachusetts',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 14,
    name: 'Ethel',
    picture: 'images/golden-retriever.jpeg',
    age: 2,
    breed: 'Golden Retriever',
    location: 'Broadlands, Oregon',
    statusText: 'Adopt',
    price: 0.001,
  },
  {
    id: 15,
    name: 'Terry',
    picture: 'images/golden-retriever.jpeg',
    age: 2,
    breed: 'Golden Retriever',
    location: 'Dawn, Wisconsin',
    statusText: 'Adopt',
    price: 0.001,
  },
]
